### ISSUE TITLE
test for centroided/missing data

### ISSUE THREAD

**Issue by sgibb** [sgibb/MALDIquant#23]
Centroided or missing mass values break our window-based baseline correction and peak detection algorithms. That's why the constructor `createMassSpectrum` has to test for centroided or missing mass values and shows a warning if needed.

**Comment by hsiaoyi0504** [comment]
So if I use `isRegular` and get the result of `TRUE`, I can conclude that my data is profile data?

**Comment by sgibb** [comment]
You are right: if `isRegular` is `TRUE` your data are in profile mode and nothing was filtered.
If `isRegular` returns `FALSE` your data are centroided or filtered (e.g. CompassXport removes m/z values which corresponding intensity values are zero from profile).

**Comment by hsiaoyi0504** [comment]
Thank you for your reply. I open an issue I found recently in here [here](https://github.com/sgibb/MALDIquantForeign/issues/19)
