### ISSUE TITLE
Add weighted average to the spectrum smoothing?

### ISSUE THREAD

**Issue by SiggiSmara** [sgibb/MALDIquant#53]
Hello,
I've added weighted average to the spectrum smoothing functions in my local fork. It is a simple one that calculates weights based on the distance from the center of the smoothing window like this:
`1/2**abs(-halfWindowSize:halfWindowSize)`
and then normalizes the weights to 1 in order not to inflate the signal.
If this of interest I'm more than happy to make a pull request.
best,
Siggi

**Comment by sgibb** [comment]
Closed via ce2ae339ea915641e87e65218e5630d0725bc438.
