### ISSUE TITLE
Averaging warping functions - plate by plate effect

### ISSUE THREAD

**Issue by SamGG** [sgibb/MALDIquant#67]
Hi,
We are running analysis of patients. Samples need to be processed on the sampling day. So about 10 samples are acquired everyday in quadruplicate. Samples are profiled in linear mode. To correct day to day m/z variation, an aliquot of a reference mix is deposited on each plate in quadruplicate. We would like to warp each spectra of a plate using the 4 reference spectra. Currently the reference spectra of all the plates are pooled and a warping function is obtained for each spectra. This leads to 4 warping functions for each plate. How to average those and get one warping function?
I am going to apply the 4 warping functions and average the resulting  masses. I am wondering if there is a better/straight way.
Best.

**Comment by sgibb** [comment]
Could you not use `averageMassSpectra` on the reference spectra and use this average spectrum for warping instead? Or use the closest (on the plate) reference spectrum for the sample?

**Comment by sgibb** [comment]
@SamGG feel free to reopen if you are not satisfied with this solution
