### ISSUE TITLE
Unable to plot MALDI-TOF proteomics data collected in reflectron mode

### ISSUE THREAD

**Issue by w2niva** [sgibb/MALDIquant#73]
Thank you for providing with MALDIquant. I have peptide MALDI-TOF MS data collected in reflectron mode. My data are in .mzML format. I am unable to plot or process the data using MALDIquant. I am using MALDIquant to generate representative spectra for my paper.
Please help!

**Comment by sgibb** [comment]
I am closing this issue because I am waiting for an answer for a long time. Please feel free to reopen it.
