### ISSUE TITLE
Quality Control

### ISSUE THREAD

**Issue by frankcorn** [sgibb/MALDIquant#74]
Greetings!
The instrument I used is AXIMA Performance from Shimadzu. 
When I ran quality control, it showed my data is centroid. I double checked my data with Shimadzu Offical document, my data is profile data. I have no idea where is the problem.
Very thanks for any help.
![image](https://user-images.githubusercontent.com/101628702/158336714-591d2ffb-403b-4bc6-a009-4b5920abdc9c.png)

**Comment by sgibb** [comment]
Sorry for the late answer. I am little bit puzzled about your question. What have you done? Please provide a minimal example. There is some heuristic to estimate profile/centroided data, if you are really sure you have profile data use `import(..., centroided = FALSE)`.

**Comment by sgibb** [comment]
I am closing this issue because I am waiting for an answer for a long time. Please feel free to reopen it.
