### ISSUE TITLE
MALDI mass spec data format

### ISSUE THREAD

**Issue by cathalgking** [sgibb/MALDIquant#78]
I have pre-processed MALDI Mass spec spatial proteomics data (Bruker company) to a table with x-y co-ordinates and m/z values (shown below). The raw data was a FeatureList file and a FullSpectra file.
Can I use MALDIquant to analyse this data format? All I want to do is basic clustering of spots to get a list of significant m/z intensity values?
![image](https://github.com/sgibb/MALDIquant/assets/32261323/0dd32978-4370-47cd-bbe7-5c2927338e95)

**Comment by sgibb** [comment]
Thanks for considering MALDIquant for your analysis. However, MALDIquant is designed for the preprocessing. MALDIquant doesn't offers any functions for clustering etc.
